### ISSUE TITLE
有文档吗

### ISSUE THREAD

**Issue by wfucksky** [freedommedal/idea-javadocs2#1]
有文档吗

**Comment by freedommedal** [comment]
访问https://plugins.jetbrains.com/plugin/12703-idea-javadocs2,有截图

**Comment by freedommedal** [comment]
> 有文档吗
有截图 访问 https://plugins.jetbrains.com/plugin/12703-idea-javadocs2

**Comment by jianjian1026** [comment]
在idea 2019.3的版本中一直提示出错,能解决一下吗
com.intellij.diagnostic.PluginException: com.github.setial.intellijjavadocs.template.DocTemplateManager requested as a service, but it is a component - convert it to a service or change call to ApplicationManager.getApplication().getComponent() [Plugin: com.sgota.plugin.idea.javadocs2]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:405)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:58)
	at com.intellij.diagnostic.PluginException.logPluginError(PluginException.java:75)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:308)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.getService(PlatformComponentManagerImpl.kt:294)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:22)
	at com.github.setial.intellijjavadocs.generator.impl.AbstractJavaDocGenerator.<init>(AbstractJavaDocGenerator.java:46)
	at com.github.setial.intellijjavadocs.generator.impl.MethodJavaDocGenerator.<init>(MethodJavaDocGenerator.java:34)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.getGenerator(JavaDocGenerateAction.java:142)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.processElement(JavaDocGenerateAction.java:113)
	at com.github.setial.intellijjavadocs.action.JavaDocGenerateAction.actionPerformed(JavaDocGenerateAction.java:103)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:298)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:83)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:149)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:313)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:604)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:657)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:193)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:656)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:517)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:472)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:221)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:830)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:775)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:424)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:423)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by freedommedal** [comment]
请检查模板内容，是velocity语法

**Comment by jianjian1026** [comment]
> 请检查模板内容，是velocity语法

我看了代码,是idea插件开发中的component 和servicce相关的东西有变更,导致2019.3版本会出这个错误提示,能抽空修复一下吗

**Comment by hzwjs** [comment]
2020.1版本也有这个问题

**Comment by hzwjs** [comment]
/**
 * Describe interface function detail.\n
 * \n
 * @author hzw \n
 * @date \n
 * @version 1.0 \n
<#if element.typeParameters?has_content>
</#if>
<#list element.typeParameters as typeParameter>
        * @param <${typeParameter.name}> the type parameter\n
</#list>
 */
---
不知模版有什么问题

**Comment by freedommedal** [comment]
已经修正
